### ISSUE TITLE
[LISTING] FUNDx

### ISSUE THREAD

**Issue by Codegnosis** [superfluid-finance/tokenlist#35]
**1. Is the token a Super Token?**
Yes

**2. Is the Super Token a Wrapper, a Pure Super Token or something else?**
Wrapper

**3. (If a Super Token Wrapper) Is the underlying token available on at least 2 reputable TokenLists [https://tokenlists.org/](https://tokenlists.org/)? If yes, skip following questions.**
No

**4. What is the link between the author of the Proposal and the Asset?**
The author is the CTO to the Unification Foundation, the issuer of the FUND token

**5. Provide a brief high-level overview of the project and the token**
Unification is a builder of permissionless, decentralised, rapidly-deployable, multi-chain toolkit for Blockchain Businesses and Permissionless Products.

The FUND ERC-20 token is bridged from our native Cosmos based chain, via the IBC protocol and Gravity Bridge chain.

**6. Explain positioning of token in the Superfluid ecosystem. Why would it be a good streaming payment asset**
Unification is in development of a new product, UNoDE, which is intended to be a privacy-first blockchain node-as-a-service (NaaS) and software-as-a-service (SaaS) platform. It will accept the ERC-20 FUND utility token as a Superfluid Subscription payment option for its services. 

**7. Provide a brief history of the project and the different components: DAO (is it live?), products (are the live?). How did it overcome some of the challenges it faced?**
Unification has been developing/growing its toolkit and product portfolio since 2017. In addition to our live Cosmos based `MainNet` blockchain, we also have EVM tools including an on-chain price oracle (OoO), and on-chain randomness generation tool (VOR).

**8. How is the asset currently used?**
FUND is Unification's native staking and tx fee token fueling the Unification ecosystem.
FUND empowers Beacons/WRKChains and will be the payment option for UNoDE 

**9. Emission schedule**
Native (Cosmos) FUND tokens are only possible to mint as eFUND through Enterprise purchases which are locked until usage and released to validators as staking rewards.

**10. Token (& Protocol) permissions (minting) and upgradability. Is there a multisig? What can it do? Who are the signers?**
The FUND ERC-20 is bridged from our native FUND token on our Cosmos based Unification MainNet. This is done via the IBC protocol and the Gravity Bridge chain, which mints and burns ERC-20 tokens as they are transferred to and from Unification MainNet/Gravity Bridge/Ethereum MainNet.

**11. Market data (Market Cap, 24h Volume, Volatility, Exchanges, Maturity)**
127,412,788.56 FUND currently in circulation
Further details can be found at: 
- https://www.coingecko.com/en/coins/unification
- https://explorer.unification.io/

**12. Social channels data (Size of communities, activity on Github)**
https://twitter.com/UnificationUND 24.8K Followers
https://t.me/UnificationOfficial 4,362 members
https://github.com/unification-com
https://medium.com/unificationfoundation

**13. Contracts date of deployments, number of transactions, number of holders for tokens**

Ethereum Mainnet FUND ERC-20 deployed on 01/11/2022
- 1,877 holders
- 8,276 transactions

**Ethereum Mainnet**
Super Token Wrapper: https://etherscan.io/address/0x479347DfD0Be56f2a5F7bB1506bFD7AB24d4BA26
Underlying ERC-20: https://etherscan.io/address/0xe9b076b476d8865cdf79d1cf7df420ee397a7f75

**Polygon Mainnet**
Super Token Wrapper: https://polygonscan.com/address/0xf1e073d53AF781966F23B1a3B2D9E67cbbA69B92
Underlying ERC-20: https://polygonscan.com/address/0x1f0145eaC900d75808510190dFC293A09c7A964F

**Ethereum Sepolia Testnet**
Super Token Wrapper: https://sepolia.etherscan.io/address/0x783fDEAB6951504C4601184587AaFED01511ED24
Underlying ERC-20: https://sepolia.etherscan.io/address/0xAfE70A1985ebDefbDCaeedba045d66091C38E1B1

**Comment by 0xdavinchee** [comment]
added fundx to tokenlist and is released in 3.2.0
